---
- name: Check ansible module
  ansible.builtin.import_playbook: playbooks/setup_module.yml
  tags: module

- name: Install components
  ansible.builtin.import_playbook: playbooks/setup_components.yml
  tags: components

- name: Install plugins for k8s
  ansible.builtin.import_playbook: playbooks/setup_k8s_plugins.yml
  tags: k8s_plugins
  when: k8s_plugins.enabled | bool

- name: Create cluster
  ansible.builtin.import_playbook: playbooks/setup_cluster.yml
  tags: cluster
  when: not ha_cluster.enabled | bool

- name: Create HA cluster
  ansible.builtin.import_playbook: playbooks/setup_ha_cluster.yml
  tags: cluster
  when: ha_cluster.enabled | bool

- name: Update CoreDNS configuration
  ansible.builtin.import_playbook: playbooks/setup_coredns.yml
  tags: coredns
  when:
    - coredns_updated is defined
    - coredns_updated | bool

- name: Add worker nodes
  ansible.builtin.import_playbook: playbooks/add_worker.yml
  tags: add_worker
  when:
    - not ha_cluster.enabled | bool
    - groups.worker | default([]) | length > 0

- name: Setup ingress controller
  ansible.builtin.import_playbook: playbooks/setup_ingress_controller.yml
  tags: ingress

- name: Setup openebs
  ansible.builtin.import_playbook: playbooks/setup_openebs.yml
  tags: openebs
  when: openebs_install | bool

- name: Setup longhorn
  ansible.builtin.import_playbook: playbooks/setup_longhorn.yml
  tags: longhorn
  when: longhorn_install | bool

- name: Setup kubevious
  ansible.builtin.import_playbook: playbooks/setup_kubevious.yml
  tags: kubevious
  when: kubevious_install | bool

- name: Setup argocd
  ansible.builtin.import_playbook: playbooks/setup_argocd.yml
  tags: argocd
  when: argocd_install | bool

- name: Setup tekton
  ansible.builtin.import_playbook: playbooks/setup_tekton.yml
  tags: tekton
  when: tekton_install | bool

- name: Setup harbor
  ansible.builtin.import_playbook: playbooks/setup_harbor.yml
  tags: harbor
  when:
    - harbor_install | bool
    - (action is undefined) or (action != "uninstall")

- name: Uninstall harbor
  ansible.builtin.import_playbook: playbooks/cleanup_harbor.yml
  tags: harbor
  when:
    - action is defined
    - action == "uninstall"

- name: Setup gitea
  ansible.builtin.import_playbook: playbooks/setup_gitea.yml
  tags: gitea
  when:
    - gitea_install | bool
    - (action is undefined) or (action != "uninstall")

- name: Uninstall gitea
  ansible.builtin.import_playbook: playbooks/cleanup_gitea.yml
  tags: gitea
  when:
    - action is defined
    - action == "uninstall"

- name: Setup kube-prometheus
  ansible.builtin.import_playbook: playbooks/setup_kube_prometheus.yml
  tags: kube_prometheus
  when: kube_prometheus_install | bool

- name: Setup octant
  ansible.builtin.import_playbook: playbooks/setup_octant.yml
  tags: octant
  when: octant_install | bool

- name: Setup openfaas
  ansible.builtin.import_playbook: playbooks/setup_openfaas.yml
  tags: openfaas
  when: openfaas_install | bool

- name: Setup cert_manager
  ansible.builtin.import_playbook: playbooks/setup_cert_manager.yml
  tags: cert_manager
  when: cert_manager_install | bool

- name: Setup jaeger
  ansible.builtin.import_playbook: playbooks/setup_jaeger.yml
  tags: jaeger
  when: jaeger_install | bool

- name: Setup linkerd
  ansible.builtin.import_playbook: playbooks/setup_linkerd.yml
  tags: linkerd
  when: linkerd_install | bool

- name: Setup velero
  ansible.builtin.import_playbook: playbooks/setup_velero.yml
  tags: velero
  when: velero_install | bool

- name: Setup awx
  ansible.builtin.import_playbook: playbooks/setup_awx.yml
  tags: awx
  when: awx_install | bool

- name: Setup st2
  ansible.builtin.import_playbook: playbooks/setup_st2.yml
  tags: st2
  when: st2_install | bool

- name: Setup kubevirt
  ansible.builtin.import_playbook: playbooks/setup_kubevirt.yml
  tags: kubevirt
  when: kubevirt_install | bool

- name: Setup metrics-server
  ansible.builtin.import_playbook: playbooks/setup_metrics_server.yml
  tags: metrics_server
  when: metrics_server_install | bool

- name: Setup reloader
  ansible.builtin.import_playbook: playbooks/setup_reloader.yml
  tags: reloader
  when: reloader_install | bool

- name: Setup kube-ps1
  ansible.builtin.import_playbook: playbooks/setup_kube_ps1.yml
  tags: kube_ps1
  when: kube_ps1_install | bool
