---
- name: Get the latest version
  ansible.builtin.import_role:
    name: github
    tasks_from: latest
  vars:
    organization: derailed
    repository: popeye
    query_string: "linux_{{ arch }}.tar.gz"

- name: Download popeye
  ansible.builtin.get_url:
    url: "{{ browser_download_url }}"
    dest: "/tmp/popeye_{{ arch }}.tar.gz"
    mode: "0644"
  become: true

- name: mkdir popeye
  ansible.builtin.file:
    path: "/tmp/popeye"
    state: directory
  become: true

- name: Extract
  ansible.builtin.unarchive:
    src: "/tmp/popeye_{{ arch }}.tar.gz"
    dest: "/tmp/popeye"
    remote_src: true
  become: true

- name: Put binary in /usr/local/bin
  ansible.builtin.copy:
    src: "/tmp/popeye/popeye"
    dest: "/usr/local/bin"
    remote_src: true
    mode: "0755"
  become: true

- name: Cleanup
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  become: true
  loop:
    - /tmp/popeye
    - "/tmp/popeye_{{ arch }}.tar.gz"
