---
- name: Get the latest version of kubecolor
  ansible.builtin.import_role:
    name: github
    tasks_from: latest
  vars:
    organization: kubecolor
    repository: kubecolor
    query_string: "linux_{{ arch }}.tar.gz"

- name: Download kubecolor
  ansible.builtin.get_url:
    url: "{{ browser_download_url }}"
    dest: "/tmp/kubecolor_{{ arch }}.tar.gz"
    mode: "0644"
  become: true

- name: Extract
  ansible.builtin.unarchive:
    src: "/tmp/kubecolor_{{ arch }}.tar.gz"
    dest: "/tmp"
    remote_src: true
  become: true

- name: Put binary in /usr/local/bin
  ansible.builtin.copy:
    src: "/tmp/kubecolor"
    dest: "/usr/local/bin"
    remote_src: true
    mode: "0755"
  become: true
